name: 🚀 Solicitação de Serviço
about: Solicite a criação ou refatoração do seu README profissional.
title: "[SERVIÇO] - "
labels: serviço, readme
assignees: reylanbit

body:
  - type: markdown
    attributes:
      value: |
        Obrigado pelo interesse! Por favor, preencha os detalhes abaixo para que possamos começar a transformar seu perfil.
  - type: dropdown
    id: plano
    attributes:
      label: Qual plano você tem interesse?
      options:
        - Essencial (R$ 60)
        - PRO (R$ 200)
    validations:
      required: true
  - type: input
    id: github-user
    attributes:
      label: Qual o seu usuário do GitHub?
      placeholder: ex: seu-usuario
    validations:
      required: true
  - type: textarea
    id: objetivos
    attributes:
      label: Quais seus principais objetivos com o novo perfil?
      placeholder: ex: Atrair recrutadores para vagas de Frontend, mostrar meus projetos pessoais, etc.
    validations:
      required: true
  - type: checkboxes
    id: contato
    attributes:
      label: Você já entrou em contato via WhatsApp?
      options:
        - label: Sim, já estamos conversando.
        - label: Não, vou entrar em contato agora.
