name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Olá! Obrigado por abrir esta issue. O Darlann entrará em contato em breve para analisar sua solicitação. 🚀"
          pr-message: "Valeu pelo PR! Analisaremos suas alterações com cuidado. 🛠️"
