name: Lint Markdown

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: "**/*.md"
